repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.20.0  # Updated to latest version
    hooks:
      - id: commitizen
        language_version: "python3.13"
        stages: ["commit-msg"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Updated to latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict  # Added to detect merge conflicts
      - id: detect-private-key  # Added for security
      - id: mixed-line-ending
        args: [--fix=lf]  # Ensures consistent line endings

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5  # Updated to latest version
    hooks:
      # run the Ruff linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # run the Ruff formatter
      - id: ruff-format

  - repo: local
    hooks:
      - id: uv-pip-check-backend
        name: Check backend dependencies with uv
        entry: bash -c 'cd backend && ../.venv/bin/uv pip check'
        language: system
        pass_filenames: false
        files: ^backend/requirements.txt$

      - id: uv-pip-check-extractor
        name: Check extractor dependencies with uv
        entry: bash -c 'cd extractor && ../.venv/bin/uv pip check'
        language: system
        pass_filenames: false
        files: ^extractor/requirements.txt$
