# User schemas
from .user import (
    UserBase,
    UserCreate,
    UserRead,
    UserUpdate,
    Token,
    TokenData,
)

# Content schemas
from .content import (
    SubjectBase,
    SubjectCreate,
    SubjectRead,
    SubjectUpdate,
    SubjectDetailedRead,
    TopicBase,
    TopicCreate,
    TopicRead,
    TopicUpdate,
    TopicWithSubjectRead,
    LessonBase,
    LessonCreate,
    LessonRead,
    LessonUpdate,
)

# Progress schemas
from .progress import (
    EnrollmentBase,
    EnrollmentCreate,
    EnrollmentRead,
    EnrollmentUpdate,
    ActivityBase,
    ActivityCreate,
    ActivityRead,
    ActivityUpdate,
    AchievementBase,
    AchievementCreate,
    AchievementRead,
    UserAchievementBase,
    UserAchievementCreate,
    UserAchievementRead,
    ActivitySummary,
    SubjectProgress,
    ProgressSummary,
    StreakInfo,
    TutoringSessionBase,
    TutoringSessionCreate,
    TutoringSessionRead,
    TutoringSessionDetailedRead,
)

# Tutoring schemas
from .tutoring import (
    TutoringExchangeBase,
    TutoringExchangeCreate,
    TutoringExchangeRead,
    TutoringExchangeUpdate,
    SessionResourceBase,
    SessionResourceCreate,
    SessionResourceRead,
    SessionResourceUpdate,
    StudentInput,
    AIResponse,
    VoiceConfig,
    OCRConfig,
    WhiteboardConfig,
)

# Recommendation schemas
from .recommendation import (
    RecommendationBase,
    RecommendationCreate,
    RecommendationRead,
    RecommendationUpdate,
)

__all__ = [
    "AchievementBase",
    "AchievementCreate",
    "AchievementRead",
    "UserAchievementBase",
    "UserAchievementCreate",
    "UserAchievementRead",
    "UserBase",
    "UserCreate",
    "UserRead",
    "UserDetailedRead",
    "UserUpdate",
    "UserPreferencesUpdate",
    "UserEducationUpdate",
    "GuardianBase",
    "GuardianCreate",
    "GuardianRead",
    "GuardianUpdate",
    "GuardianWithStudentInfo",
    "Token",
    "TokenData",
    "SubjectBase",
    "SubjectCreate",
    "SubjectRead",
    "SubjectUpdate",
    "SubjectDetailedRead",
    "TopicBase",
    "TopicCreate",
    "TopicRead",
    "TopicUpdate",
    "TopicWithSubjectRead",
    "LessonBase",
    "LessonCreate",
    "LessonRead",
    "LessonUpdate",
    "EnrollmentBase",
    "EnrollmentCreate",
    "EnrollmentRead",
    "EnrollmentUpdate",
    "ActivityBase",
    "ActivityCreate",
    "ActivityRead",
    "ActivityUpdate",
    "ActivitySummary",
    "SubjectProgress",
    "ProgressSummary",
    "StreakInfo",
    "TutoringSessionBase",
    "TutoringSessionCreate",
    "TutoringSessionRead",
    "TutoringSessionDetailedRead",
    "TutoringExchangeBase",
    "TutoringExchangeCreate",
    "TutoringExchangeRead",
    "TutoringExchangeUpdate",
    "SessionResourceBase",
    "SessionResourceCreate",
    "SessionResourceRead",
    "SessionResourceUpdate",
    "StudentInput",
    "AIResponse",
    "VoiceConfig",
    "OCRConfig",
    "WhiteboardConfig",
    "RecommendationBase",
    "RecommendationCreate",
    "RecommendationRead",
    "RecommendationUpdate",
]
